agent: "CBDDQN"
env_name: "MiniGrid"
env_id: "MiniGrid-SimpleCrossingS11N5-v0"
RGBImgPartialObsWrapper: False
ImgObsWrapper: False
vectorize: "Dummy_MiniGrid"
policy: "Basic_Q_network"
#policy: "Categorical_AC"
representation: "Basic_MLP"
runner: "DRL"
representation_hidden_size: [64,]
q_hidden_size: [64,]
activation: 'relu'

seed: 123
parallels: 10
buffer_size: 10000
batch_size: 256
learning_rate: 0.001
gamma: 0.99

start_greedy: 0.5
end_greedy: 0.01
decay_step_greedy: 200000
sync_frequency: 50
training_frequency: 1
running_steps: 2000000  # 200k
start_training: 1000

k: 4
n_clusters: 10
beta_max: 0.5

use_obsnorm: False
use_rewnorm: False
obsnorm_range: 5
rewnorm_range: 5

model_dir: "models/final_train_model(1).pth"

test_steps: 10000
eval_interval: 20000
test_episode: 100
log_dir: "./logs/cbddqn/"
model_dir: "./models/cbddqn/"